version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./docker/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini # XDebug ayarlarını bağlamak için
    ports:
      - "8080:80"
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
