version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: duck_scraper/src/Dockerfile
    volumes:
      - ./duck_scraper/src:/var/www/html
      - ./duck_scraper/src/docker/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./duck_scraper/src
    ports:
      - "8080:80"
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    user: root
    command: >
        bash -c "
          composer install --optimize-autoloader &&
          apache2-foreground
        "
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
